MemcConns:
  idfa: 127.0.0.1:33013
  gaid: 127.0.0.1:33014
  adid: 127.0.0.1:33015
  dvid: 127.0.0.1:33016
Memc:
  RetryTimeout: 3
  # Max conn timeout in seconds
  ConnTimeout: 5
  RetryCount: 3
  # Max number of simultaneous connections for memc cache
  MaxConnectionPerServer: 10
# Max number of simultaneous open files for analyzing
MaxOpenFiles: 10
# Multiplication for number of CPU for goroutine for analyze line
MaxLineAnalyzerMul: 5