version: '3.7'

services:

  pg:
    image: postgres:11.1-alpine
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:1.15.8-alpine

volumes:
  pg_data: {}
